-- =============================================================
-- Snowflake Database & Schema Setup
-- Data Lakehouse POC — Gold Layer
-- =============================================================

-- Database
CREATE DATABASE IF NOT EXISTS DATALAKEHOUSE;
USE DATABASE DATALAKEHOUSE;

-- Schemas
CREATE SCHEMA IF NOT EXISTS GOLD;
CREATE SCHEMA IF NOT EXISTS STAGING;

-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
    WITH WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Roles
CREATE ROLE IF NOT EXISTS DATA_READER;
CREATE ROLE IF NOT EXISTS DATA_WRITER;

GRANT USAGE ON DATABASE DATALAKEHOUSE TO ROLE DATA_READER;
GRANT USAGE ON SCHEMA DATALAKEHOUSE.GOLD TO ROLE DATA_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA DATALAKEHOUSE.GOLD TO ROLE DATA_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DATALAKEHOUSE.GOLD TO ROLE DATA_READER;

GRANT USAGE ON DATABASE DATALAKEHOUSE TO ROLE DATA_WRITER;
GRANT ALL PRIVILEGES ON SCHEMA DATALAKEHOUSE.GOLD TO ROLE DATA_WRITER;
GRANT ALL PRIVILEGES ON SCHEMA DATALAKEHOUSE.STAGING TO ROLE DATA_WRITER;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DATA_READER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DATA_WRITER;
